### ISSUE TITLE
Your binary EXE file (in Releases) is a malware!

### ISSUE THREAD

**Issue by alMubarmij** [sergiye/openhardwaremonitor#3]
https://github.com/sergiye/openhardwaremonitor/releases/download/1.0.8912/OpenHardwareMonitor.exe

Here is a VirusTotal result:
https://www.virustotal.com/gui/file/bad73bc3c674b2036a3c59f1f0e611fc16e931890ae4230cbca0aca2877f5a73/detection/f-bad73bc3c674b2036a3c59f1f0e611fc16e931890ae4230cbca0aca2877f5a73-1729769271

Please, remove it and don't do that again here!

**Comment by sergiye** [comment]
please don't create duplicated issues every day

**Comment by sergiye** [comment]
ok, let's reopen the old one => https://github.com/sergiye/openhardwaremonitor/issues/2
if you have any suggestions please write there
